package com.Raiti.SomeEatingItems.ASM;

import net.minecraftforge.fml.common.DummyModContainer;
import net.minecraftforge.fml.common.LoadController;
import net.minecraftforge.fml.common.ModMetadata;

import com.google.common.eventbus.EventBus;

/**
 * SomeEatingItemsCorePlugin's metadata.
 * This class is MetadataClass.
 * <br>Created by Raiti-chan on 2017/03/06.
 *
 * @author Raiti-chan
 * @version 1.0.0
 * @since 1.0.0
 */
public class SomeEatingItemsDummyContainer extends DummyModContainer {
	
	/**
	 * Write data.
	 * 
	 */
	public SomeEatingItemsDummyContainer(){
		super(new ModMetadata());
		ModMetadata metadata = getMetadata();
		metadata.name = "SomeEatingItemsCorePlugin";
		metadata.modId = "seicoreplugin";
		metadata.version = "1.11.x-1.0.0 β";
		metadata.authorList.add("Raiti-chan");
		setEnabledState(true);
		metadata.autogenerated = false;
	}
	
	/**
	 * Register the event bus for the mod and the controller for error handling
	 * Returns if this bus was successfully registered - disabled mods and other
	 * mods that don't need real events should return false and avoid further
	 * processing
	 *
	 * @param bus bus
	 * @param controller controller
	 */
	@Override
	public boolean registerBus (EventBus bus, LoadController controller) {
		bus.register(this);
		return true;
	}
}
